### ISSUE TITLE
Map alt+v to ź

### ISSUE THREAD

**Issue by konrad-kruczynski** [taw/osx-keyboard-layouts#1]
Hi,
first of all thank you for your layout! This was one of the first things I've looked for after receiving my Mac. I have one feature request though. When I created my own polish dvorak mapping on Linux, I decided to map ctrl+v for ź (instead of x). This is since the original choice was due to x location directly to z. Also note that this is much more handy. What do you think?

**Comment by taw** [comment]
I know some people move it, I'm just used to the original way :-)

If you want to pull request that, I can include alternative layout too.

**Comment by konrad-kruczynski** [comment]
Done.
