### ISSUE TITLE
Switch to QWERTY on Command

### ISSUE THREAD

**Issue by swilgosz** [taw/osx-keyboard-layouts#4]
Is it possible to switch to qwerty after pressing CMD button?

It would be nice for keeping whole standard key shortcuts for lot of apps.

**Comment by taw** [comment]
It's definitely possible, and I know there's English Dvorak variant which does that.
I like it the way it is, but if you'd like to submit such hybrid keymap, it would be welcome of course.

(or I could take a look at making one, but a bit busy at the moment)

**Comment by taw** [comment]
Looks like I completely forgot about it. Is it still something that interests you?

**Comment by swilgosz** [comment]
Well, I actually abandoned the idea to switch to DVORAK as while it's great for writers, not so great for developers.

Most of the applications for developers have their shortcuts being prepared to be easily accessible with CMD/CTRL combinations and in DVORAK layout it starts to become really tricky sometimes to use them.

That's especially important for code editors. You can close this one if I'm the only one interested in this feature ;)
